apiVersion: v2
name: redis
description: A Helm chart for Redis

version: 0.1.0

appVersion: 7.0.12

annotations:
  category: Database
  licenses: Apache-2.0

dependencies:
- name: redis
  version: 17.11.7
  repository: https://charts.bitnami.com/bitnami
 
