apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-server
  template:
    metadata:
      labels:
        app: example-server
    spec:
      containers:
      - name: example-server
        image: example-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-server
spec:
  selector:
    app: example-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-client
  template:
    metadata:
      labels:
        app: example-client
    spec:
      containers:
      - name: example-client
        image: example-client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-client
spec:
  selector:
    app: example-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001
  type: NodePort
